### ISSUE TITLE
Be safe and dont use mouse inputs with python

### ISSUE THREAD

**Issue by MSHookFunction** [the-lne/mwIII_2023-psbb#1]
The anti cheat definitely detects the mouse events from the python script, try sticking to just movements or use keybinds to look around. Cant wait to see if this algorithm is real

**Comment by the-lne** [comment]
Oh I thought using the win32 module for mouse input would save me. Thanks for the tip. I haven't got banned yet but bans do tend to happen in waves on bigger games so I probably have one coming lol.
